<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FH0MTAT" failures="1" tests="12" name="com.QaLegandProject.scripts.CustomerTest" time="11.861" errors="1" timestamp="2023-06-29T15:34:30 IST" skipped="5">
  <testcase classname="com.QaLegandProject.scripts.CustomerTest" name="takeScreenShotOnFailure" time="0.003">
    <error message="Cannot format given Object as a Date" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Cannot format given Object as a Date
at java.base/java.text.DateFormat.format(DateFormat.java:342)
at java.base/java.text.Format.format(Format.java:159)
at com.QaLegandProject.Base.TestBase.takeScreenShotOnFailure(TestBase.java:65)
at com.QaLegandProject.Base.TestBase.takeScreenShotOnFailure(TestBase.java:60)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.internal.invokers.TestInvoker.runConfigMethods(TestInvoker.java:823)
at org.testng.internal.invokers.TestInvoker.runAfterConfigurations(TestInvoker.java:792)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:768)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- takeScreenShotOnFailure -->
  <system-out/>
  <testcase classname="com.QaLegandProject.scripts.CustomerTest" name="verifyingShowEntries" time="0.136"/>
  <system-out/>
  <testcase classname="com.QaLegandProject.scripts.CustomerTest" name="deleteselectedrow" time="0.902"/>
  <system-out/>
  <testcase classname="com.QaLegandProject.scripts.CustomerTest" name="verifyingClientAddition" time="0.358"/>
  <system-out/>
  <testcase classname="com.QaLegandProject.scripts.CustomerTest" name="verifyingPageNavigation" time="0.529"/>
  <system-out/>
  <testcase classname="com.QaLegandProject.scripts.CustomerTest" name="checkcalender" time="0.105"/>
  <system-out/>
  <testcase classname="com.QaLegandProject.scripts.CustomerTest" name="verifyingpictureUpload" time="1.565">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at com.QaLegandProject.scripts.CustomerTest.verifyingpictureUpload(CustomerTest.java:81)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyingpictureUpload -->
  <system-out/>
  <testcase classname="com.QaLegandProject.scripts.CustomerTest" name="verifyingpictureUpload" time="1.615">
    <skipped/>
  </testcase> <!-- verifyingpictureUpload -->
  <system-out/>
  <testcase classname="com.QaLegandProject.scripts.CustomerTest" name="verifyingpictureUpload" time="1.680">
    <skipped/>
  </testcase> <!-- verifyingpictureUpload -->
  <system-out/>
  <testcase classname="com.QaLegandProject.scripts.CustomerTest" name="verifyingpictureUpload" time="1.613">
    <skipped/>
  </testcase> <!-- verifyingpictureUpload -->
  <system-out/>
  <testcase classname="com.QaLegandProject.scripts.CustomerTest" name="verifyingpictureUpload" time="1.710">
    <skipped/>
  </testcase> <!-- verifyingpictureUpload -->
  <system-out/>
  <testcase classname="com.QaLegandProject.scripts.CustomerTest" name="verifyingpictureUpload" time="1.645">
    <skipped/>
  </testcase> <!-- verifyingpictureUpload -->
  <system-out/>
</testsuite> <!-- com.QaLegandProject.scripts.CustomerTest -->
